### ISSUE TITLE
`reentry` uses the same datafile for different virtual environments

### ISSUE THREAD

**Issue by mbercx** [aiidateam/reentry#67]
When you have multiple AiiDA installations on the same machine, but in different environments, `reentry` (sometimes?) uses the same datafile:

```console
aiida@prnmarvelsrv3:~$ workon aiida-lumi
(aiida-lumi) aiida@prnmarvelsrv3:~$ reentry dev datafile
/home/aiida/.config/reentry/data/356c687cacee0a69fdc380f67c838f44267aa1c10563d364001fb6dcf7bf6876
(aiida-lumi) aiida@prnmarvelsrv3:~$ workon aiida-cwf
(aiida-cwf) aiida@prnmarvelsrv3:~$ reentry dev datafile
/home/aiida/.config/reentry/data/356c687cacee0a69fdc380f67c838f44267aa1c10563d364001fb6dcf7bf6876
```

This is problematic when the virtual environments have packages with different entry points installed. The reason this happens ​is because the `hashed_data_file_name` function uses the `resolve()` method on the `Path` of the Python executable:

https://github.com/aiidateam/reentry/blob/577e5bbf6bde5b81b6ee6125e2f300636959389b/reentry/config.py#L71-L79

and the Python executables of two different environments can in some cases be a symlink to the same Python executable:

```python
In [1]: import sys; from pathlib import Path

In [2]: Path(sys.executable)
Out[2]: PosixPath('/home/aiida/.virtualenvs/aiida-lumi/bin/python')

In [3]: Path(sys.executable).resolve()
Out[3]: PosixPath('/usr/bin/python3.8')
```

To avoid that running `reentry scan` in one environment overrides the entry points of another environment, you can remove the `resolve()` method in line 74 of the config file, i.e.:

```python
     fname = 'u{bin_dir}_{impl}-{ver}'.format(bin_dir=Path(sys.executable).parent, 
                                              impl=platform.python_implementation(), 
                                              ver=platform.python_version())
```

I've tried this for my environments, and it seems to work fine. Since `reentry` is no longer used from AiiDA v2.0 onwards, I just wanted to describe the solution to this issue here for others using AiiDA 1.X with multiple environments on the same machine. If many users are running into this issue, we might consider making a new release with this change, unless removing `resolve()` has other unintended consequences?

**Comment by ltalirz** [comment]
Thanks for pointing out this subtlety; I guess we transitioned to pathlib at some point but did not consider that [`Path.resolve()` resolves symlinks while `os.path.abspath()` doesn't](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module).

If you'd like to make a small PR to use `os.path.abspath()` there I'd be happy to review it and mint a new patch release.
